# This reusable workflow downloads the build artifact and publishes it to npm.
name: Publish to npm

on:
  workflow_call:
    inputs:
      node-version:
        description: "Node.js version to use for publishing (e.g., '16', '18', '20', '22')"
        required: false
        type: string
        default: '22'
    secrets:
      NPM_TOKEN:
        description: "npm token with publish permissions"
        required: true

jobs:
  publish:
    name: Publish Package to npm
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: library-dist
          path: library-dist

      - name: Setup Node.js for publishing
        uses: actions/setup-node@v4
        with:
          node-version: '${{ inputs.node-version }}'
          registry-url: 'https://registry.npmjs.org'

      - name: Publish to npm
        run: npm publish ./library-dist
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
